import Link from 'next/link'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  console.log("montando layout")
  return (
    <html lang="en">
      <body>
        <div>
          Menu principal: <Link href="/">Home</Link> | <Link href="/novarota">Nova rota</Link>
        </div>
        <hr/>
        {children}
      </body>
    </html>
  )
}